# Generated by Django 5.0.7 on 2024-08-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_one', models.CharField(default='Competition and Tariff Commission', max_length=255)),
                ('header_two', models.CharField(blank=True, max_length=255, null=True)),
                ('button_text', models.CharField(default='Read more', max_length=255)),
                ('button_link', models.URLField(max_length=255)),
                ('background_image', models.ImageField(upload_to='slider')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
