# Generated by Django 5.0.7 on 2024-08-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_folder_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('', 'Select a Category'), ('COMESA_COMPETITION_COMMISSION', 'Comesa Competition Commission'), ('COMMISSION_DECISIONS', 'Commission Decisions'), ('FORMS', 'Forms'), ('LEGAL_AND_CORPORATE_ISSUES', 'Legal & Corporate Issues'), ('GUIDELINES', 'Guidelines'), ('BROCHURES', 'Brochures'), ('POLICIES', 'BROCHURES')], max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='files/%Y/%m/%d/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
