# Generated by Django 5.0.7 on 2024-08-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_download'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('', 'Select a Category'), ('BOARD_OF_COMMISSIONERS', 'Board of Commissioners'), ('MANAGEMENT', 'Management'), ('STAFF_MEMBER', 'Staff Member')], max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(upload_to='profile_picture/%Y/%m/%d/')),
                ('facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter', models.URLField(blank=True, max_length=255, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
