# Generated by Django 5.0.7 on 2024-08-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='file_size',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
