# Generated by Django 5.0.7 on 2024-08-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_download_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('', 'Select a Category'), ('board-of-commissioners', 'Board of Commissioners'), ('management', 'Management'), ('staff-member', 'Staff Member')], max_length=255),
        ),
    ]
