# Generated by Django 5.0.7 on 2024-08-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_team_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='full_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
