# Generated by Django 5.0.7 on 2024-09-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_division_delete_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='category',
            field=models.CharField(choices=[('', 'Select a Category'), ('comesa-competition-commission', 'Comesa Competition Commission'), ('commission-decisions', 'Commission Decisions'), ('forms', 'Forms'), ('legal-and-corporate-issues', 'Legal & Corporate Issues'), ('guidelines', 'Guidelines'), ('brochures', 'Brochures'), ('policies', 'Policies')], max_length=255),
        ),
    ]
