# Generated by Django 5.0.7 on 2024-09-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_download_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='file_size',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
