# Generated by Django 5.0.7 on 2024-09-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_media_alter_download_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='header_one_color',
            field=models.CharField(default='#0E1089', max_length=255),
        ),
        migrations.AddField(
            model_name='slider',
            name='header_two_color',
            field=models.CharField(default='#ffffff', max_length=255),
        ),
    ]
