# Generated by Django 5.0.7 on 2024-09-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_slider_header_one_color_slider_header_two_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='button_color',
            field=models.CharField(default='#0E1089', max_length=255),
        ),
    ]
