# Generated by Django 5.0.7 on 2024-09-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_slider_button_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(default='', upload_to='news/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
