# Generated by Django 5.0.7 on 2024-09-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='category',
            field=models.CharField(choices=[('', 'Select a Category'), ('comesa-competition-commission', 'Comesa Competition Commission'), ('commission-decisions', 'Commission Decisions'), ('forms', 'Forms'), ('legal-and-corporate-issues', 'Legal & Corporate Issues'), ('guidelines', 'Guidelines'), ('brochures', 'Brochures'), ('policies', 'Policies'), ('annual-reports', 'Annual Reports'), ('newsletter', 'Newsletter'), ('strategic-plan', 'Strategic Plan'), ('stakeholder-consultations', 'Stakeholder Consultations'), ('sector-studies', 'Sector Studies'), ('african-competition-forum-studies', 'African Competition Forum Studies'), ('analytical-papers', 'Analytical Papers')], max_length=255, unique=True),
        ),
    ]
