# Generated by Django 5.0.7 on 2024-09-30 08:34

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_download_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legislation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='legislation', max_length=255, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='download',
            name='category',
            field=models.CharField(choices=[('', 'Select a Category'), ('comesa-competition-commission', 'Comesa Competition Commission'), ('commission-decisions', 'Commission Decisions'), ('forms', 'Forms'), ('legal-and-corporate-issues', 'Legal & Corporate Issues'), ('guidelines', 'Guidelines'), ('brochures', 'Brochures'), ('policies', 'Policies'), ('annual-reports', 'Annual Reports'), ('newsletter', 'Newsletter'), ('strategic-plan', 'Strategic Plan'), ('stakeholder-consultations', 'Stakeholder Consultations'), ('sector-studies', 'Sector Studies'), ('african-competition-forum-studies', 'African Competition Forum Studies'), ('analytical-papers', 'Analytical Papers'), ('complaints-form-relating-to-restrictive-practices', 'Complaints Form relating to Restrictive Practices'), ('merger-notification-form', 'Merger Notification Form'), ('dumping-form', 'Dumping Form')], max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='LegislationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.CharField(default='0', max_length=255)),
                ('file', models.FileField(upload_to='legislation/%Y/%m/%d/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.legislation')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
