# Generated by Django 5.0.7 on 2024-09-30 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_legislation_alter_download_category_legislationfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislationfile',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legislation_files', to='core.legislation'),
        ),
    ]
