# Generated by Django 5.0.7 on 2024-09-30 09:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_legislationfile_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('', 'Select a category'), ('full-time', 'Full time'), ('part-time', 'Part time'), ('remote', 'Remote'), ('project', 'Project')], max_length=100)),
                ('job_title', models.CharField(max_length=255)),
                ('closing_date', models.DateField()),
                ('published', models.BooleanField(default=False)),
                ('file_size', models.CharField(default='0', max_length=255)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='job/%Y/%m/%d/')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
