# Generated by Django 5.0.7 on 2024-09-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
