# Generated by Django 5.0.7 on 2024-11-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_vacancy_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_size', models.CharField(default='0', max_length=255)),
                ('link', models.URLField()),
                ('logo', models.FileField(blank=True, null=True, upload_to='job/%Y/%m/%d/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
