# Generated by Django 5.0.7 on 2024-11-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_emblem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_size', models.CharField(default='0', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='tenders/%Y/%m/%d/')),
                ('due_date', models.DateField()),
                ('time', models.TimeField()),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='emblem',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='emblem/%Y/%m/%d/'),
        ),
    ]
