# Generated by Django 5.0.7 on 2025-05-27 07:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_download_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCharter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('english_charter', models.FileField(blank=True, help_text='Upload English version of the charter', null=True, upload_to='charters/english/%Y/%m/%d/')),
                ('shona_charter', models.FileField(blank=True, help_text='Upload Shona version of the charter', null=True, upload_to='charters/shona/%Y/%m/%d/')),
                ('ndebele_charter', models.FileField(blank=True, help_text='Upload Ndebele version of the charter', null=True, upload_to='charters/ndebele/%Y/%m/%d/')),
                ('slug', models.SlugField(unique=True)),
                ('published', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client Charter',
                'verbose_name_plural': 'Client Charters',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={},
        ),
        migrations.AlterField(
            model_name='download',
            name='category',
            field=models.CharField(choices=[('', 'Select a Category'), ('comesa-competition-commission', 'Comesa Competition Commission'), ('commission-decisions', 'Commission Decisions'), ('forms', 'Forms'), ('legal-and-corporate-issues', 'Legal & Corporate Issues'), ('guidelines', 'Guidelines'), ('brochures', 'Brochures'), ('policies', 'Policies'), ('annual-reports', 'Annual Reports'), ('newsletter', 'Newsletter'), ('strategic-plan', 'Strategic Plan'), ('stakeholder-consultations', 'Stakeholder Consultations'), ('sector-studies', 'Sector Studies'), ('african-competition-forum-studies', 'African Competition Forum Studies'), ('analytical-papers', 'Analytical Papers'), ('complaints-form-relating-to-restrictive-practices', 'Complaints Form relating to Restrictive Practices'), ('merger-notification-form', 'Merger Notification Form'), ('dumping-form', 'Dumping Form'), ('summary-merger-decisions', 'Summary Merger\xa0Decisions'), ('summary-merger-decisions', 'Summary Merger\xa0Decisions')], max_length=255, unique=True),
        ),
    ]
