# Generated by Django 5.0.7 on 2025-05-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_clientcharter_alter_vacancy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='category',
            field=models.CharField(choices=[('', 'Select a Category'), ('comesa-competition-commission', 'Comesa Competition Commission'), ('commission-decisions', 'Commission Decisions'), ('forms', 'Forms'), ('legal-and-corporate-issues', 'Legal & Corporate Issues'), ('guidelines', 'Guidelines'), ('brochures', 'Brochures'), ('policies', 'Policies'), ('annual-reports', 'Annual Reports'), ('newsletter', 'Newsletter'), ('strategic-plan', 'Strategic Plan'), ('stakeholder-consultations', 'Stakeholder Consultations'), ('sector-studies', 'Sector Studies'), ('african-competition-forum-studies', 'African Competition Forum Studies'), ('analytical-papers', 'Analytical Papers'), ('complaints-form-relating-to-restrictive-practices', 'Complaints Form relating to Restrictive Practices'), ('merger-notification-form', 'Merger Notification Form'), ('dumping-form', 'Dumping Form'), ('summary-merger-decisions', 'Summary Merger\xa0Decisions'), ('summary-merger-decisions', 'Summary Merger\xa0Decisions')], max_length=255),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='job_type',
            field=models.CharField(choices=[('', 'Select a category'), ('full-time', 'Full time'), ('part-time', 'Part time'), ('remote', 'Remote'), ('project', 'Project'), ('contract', 'Contract')], max_length=100),
        ),
    ]
