# Generated by Django 5.0.7 on 2025-05-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_download_category_alter_vacancy_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='category',
            field=models.CharField(choices=[('competition', 'Competition'), ('research', 'Research Unit'), ('tariffs', 'Tariffs'), ('legal', 'Legal & Corporate Services'), ('finance', 'Finance and Administration')], max_length=50, null=True),
        ),
    ]
